Assets folder update

diff --git a/assets/usr/bin/sensible-browser b/assets/usr/bin/sensible-browser
--- a/assets/usr/bin/sensible-browser
+++ b/assets/usr/bin/sensible-browser
@@ -1,24 +1,15 @@
 #!/bin/sh
 
 # Prevent recursive loops, where these values are set to this script
-p="$(command -v "$0")"
-[ -n "$BROWSER" ] && [ "$(command -v "$BROWSER" || true)" = "$p" ] && BROWSER=
-
-IsError()
-{
-	# Operating system command not found
-	[ "$1" -ne 126 ] && [ $1 -ne 127 ]
-}
-
-Run()
-{
-	"$@"
-	ret=$?
-	IsError "$ret"
-}
+p="$(which sensible-browser)"
+[ -n "$BROWSER" ] && [ "$(which $BROWSER || true)" = "$p" ] && BROWSER=
 
 if test -n "$BROWSER"; then
-    Run "${BROWSER}" "$@" && exit "$ret"
+    ${BROWSER} "$@"
+    ret="$?"
+    if [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ]; then
+	exit "$ret"
+    fi
 fi
 
 if test -n "$DISPLAY"; then
@@ -40,6 +31,6 @@ elif test -x /usr/bin/www-browser; then
     exec /usr/bin/www-browser "$@"
 fi
 
-echo "Couldn't find a suitable web browser!\n" >&2
-echo "Set the BROWSER environment variable to your desired browser.\n" >&2
+printf "Couldn't find a suitable web browser!\n" >&2
+printf "Set the BROWSER environment variable to your desired browser.\n" >&2
 exit 1;
diff --git a/assets/var/lib/dpkg/info/libc6:amd64.preinst b/assets/var/lib/dpkg/info/libc6:amd64.preinst
--- a/assets/var/lib/dpkg/info/libc6:amd64.preinst
+++ b/assets/var/lib/dpkg/info/libc6:amd64.preinst
@@ -19,52 +19,90 @@ kfreebsd_compare_versions () {
     test $verA -$2 $verB
 }
 
+# Sanity check.
+# If there are versions of glibc outside of the normal installation
+# location (/lib, /lib64, etc.) then things may break very badly
+# as soon as ld.so is replaced by a new version.  This check is not
+# foolproof, but it's pretty accurate.  This script ignores libraries
+# with different sonames, and libraries incompatible with the 
+# to-be-installed ld.so.
+check_dir () {
+    msg=$1
+    dir=$2
+
+    # Follow symlinks
+    dir=$(readlink -e $dir || true)
+
+    # Ignore inexistent directories
+    if ! test -d "$dir" ; then
+        return
+    fi
+  
+    # Detect possible candidates
+    files=$(ls $dir | egrep '^(ld|lib(d|c|m|pthread|rt|dl))-2.*.so' 2>/dev/null || true)
+    if test -z "$files" ; then
+        return
+    fi
+  
+    for file in $files ; do
+        lib=$dir/$file
+
+        # Skip if it is a symlink (as installed by lsb-core)
+        if test -L "$lib" ; then
+            continue
+        fi
+
+        # Skip if it is the currently dynamic loader
+        if test "$lib" = "$ldfile" ; then
+            continue
+        fi
+
+        # See if the found libraries are compatible with the system ld.so;
+        # if they aren't, they'll be ignored. Check e_ident, e_type (which
+        # will just be ET_DYN), and e_machine. If a match is found, there
+        # is a risk of breakage.
+        libbytes=`head -c 20 $lib | od -c`
+        if test "$ldbytes" != "$libbytes" ; then 
+          continue
+        fi
+
+        # Binaries owned packages are considered to do the right thing
+        # First try a quick lookup which should catch all cases on a 
+        # normal system
+        if echo $libcfiles | grep -q "[ ^]$lib[ $]" ; then 
+            continue
+        fi
+
+        # Slower lookup to confirm
+        if dpkg-query -S "$lib" >/dev/null 2>&1 ; then
+            continue
+        fi
+
+        # Output an error message and exit
+        echo
+        echo "A copy of the C library was found $msg:"
+        echo "  '$lib'"
+        echo "It is not safe to upgrade the C library in this situation;"
+        echo "please remove that copy of the C library or get it out of"
+        echo "'$dir' and try again."
+        echo
+        exit 1
+    done
+}
+
 if [ -n "$preversion" ] && dpkg --compare-versions "$preversion" lt 2.31-0ubuntu2; then
-	LDCONFIG_NOTRIGGER=y
+	LCONFIG_NOTRIGGER=y
 	export LDCONFIG_NOTRIGGER
 	ldconfig || ldconfig --verbose
 fi
 
-if [ "$type" != abort-upgrade -a -z "$DPKG_ROOT" ]
+if [ "$type" != abort-upgrade ]
 then
     # Load debconf module if available and usable
-    if [ -f /usr/share/debconf/confmodule ]; then
-        # cdebconf has a working fallback mechanism in case dialog
-        # is not usable, so do not try to do anything smart here
-        if [ "$DEBCONF_USE_CDEBCONF" ] ; then
-            . /usr/share/debconf/confmodule
-            USE_DEBCONF=1
-        # debconf requires perl
-        elif perl -e "" 2>/dev/null ; then
-            . /usr/share/debconf/confmodule
-            # Check that the selected frontend will work
-            if [ -n "$DEBIAN_FRONTEND" ] ; then
-                frontend="$DEBIAN_FRONTEND"
-            else
-                db_version 2.0
-                db_get debconf/frontend || RET="Dialog"
-                frontend="$RET"
-            fi
-            frontend=`echo $frontend | tr '[:upper:]' '[:lower:]'`
-            case "$frontend" in
-            dialog)
-                # debconf uses whiptail by default unless dialog is available and
-                # $DEBCONF_FORCE_DIALOG is set
-                if [ -x "$(which whiptail)" ] && ! ( [ -n "$DEBCONF_FORCE_DIALOG" ] && [ -x "$(which dialog)" ] ); then
-                    frontend=whiptail
-                fi
-                # Only enable debconf if the whiptail/dialog are not available
-                # (in which case debconf has a fallback mechanism) or usable
-                if ! [ -x "$(which $frontend)" ] || $frontend --version > /dev/null 2>&1 ; then
-                    USE_DEBCONF=1
-                fi
-                ;;
-            *)
-                 # For now assume that all other frontends are fine
-                 USE_DEBCONF=1
-                ;;
-            esac
-        fi
+    if [ -f /usr/share/debconf/confmodule ] && \
+       ( [ "$DEBCONF_USE_CDEBCONF" ] || perl -e "" 2>/dev/null ) ; then
+        . /usr/share/debconf/confmodule
+        USE_DEBCONF=1
     fi
 
     # See if LD_LIBRARY_PATH contains the traditional /lib, but not the
@@ -96,6 +134,21 @@ then
     system=`uname -s`
     if [ "$system" = "Linux" ]
     then
+        # Test to make sure z < 255, in x.y.z-n form of kernel version
+        # Also make sure we don't trip on x.y.zFOO-n form
+        kernel_rev=$(uname -r | sed 's/\([0-9]*\.\)\{1,2\}\([0-9]*\)\(.*\)/\2/')
+        if [ "$kernel_rev" -ge 255 ]
+        then
+            echo "ERROR: Your kernel version indicates a revision number"
+            echo "of 255 or greater.  Glibc has a number of built in"
+            echo "assumptions that this revision number is less than 255."
+            echo "If you\'ve built your own kernel, please make sure that any"
+            echo "custom version numbers are appended to the upstream"
+            echo "kernel number with a dash or some other delimiter."
+            echo
+            exit 1
+        fi
+
         # sanity checking for the appropriate kernel on each architecture.
         kernel_ver=`uname -r`
         case ${DPKG_MAINTSCRIPT_ARCH} in
@@ -172,11 +225,59 @@ then
     fi
 fi
 
-if [ "$type" = upgrade -a -z "$DPKG_ROOT" ]
+if [ "$type" = upgrade ]
 then
+    # Try to detect copies of the libc library in the various places
+    # the dynamic linker uses.
+    ldfile=$(readlink -m /lib64/ld-linux-x86-64.so.2)
+    if test -f "$file"; then
+        ldbytes=$(head -c 20 /lib64/ld-linux-x86-64.so.2 | od -c)
+    else
+        # If the symlink to the dynamic linker is dangling or missing, set
+        # ldbytes to an empty string, the test below will fail and all the
+        # libraries found will be ignored.
+        ldbytes=""
+    fi
+    libcfiles=$(dpkg-query -L ${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} 2>/dev/null)
+
+    dirs="/lib/x86_64-linux-gnu /lib /lib/tls /lib32 /lib64 /usr/local/lib /usr/local/lib32 /usr/local/lib64"
+    for dir in $dirs ; do
+        check_dir "in an unexpected directory" $dir
+    done
+
+    if test -n "$LD_LIBRARY_PATH"; then
+        dirs=$(echo $LD_LIBRARY_PATH | sed 's/:/ /g')
+        for dir in $dirs ; do
+            check_dir "via LD_LIBRARY_PATH" $dir
+        done
+    fi
+
+    if test -e /etc/ld.so.conf; then
+        dirs=$(echo $(cat /etc/ld.so.conf))
+        if test -n "$dirs" ; then
+            for dir in $dirs ; do
+                check_dir "via /etc/ld.so.conf" $dir
+            done
+        fi
+    fi
+
+    if [ -e /lib/tls/i686/cmov/libc.so.6 ] || [ -e /lib/i686/cmov/libc.so.6 ] ; then
+        status_i686=$(dpkg -s libc6-i686 2>/dev/null | grep ^Status: | sed -e 's/^Status: \(.*\) \(.*\) \(.*\)/\3/g')
+        status_xen=$(dpkg -s libc6-xen 2>/dev/null | grep ^Status: | sed -e 's/^Status: \(.*\) \(.*\) \(.*\)/\3/g')
+        if ([ -z "$status_i686" ] || [ "$status_i686" = "not-installed" ] || [ "$status_i686" = "config-files" ]) && \
+             ([ -z "$status_xen" ] || [ "$status_xen" = "not-installed" ] || [ "$status_xen" = "config-files" ]); then
+            echo
+            echo "A non-dpkg owned copy of the libc6-i686 package was found."
+            echo "It is not safe to upgrade the C library in this situation;"
+            echo "please remove that copy of the C library and try again."
+            echo
+            exit 1
+        fi
+    fi
+
     if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
 	# NSS authentication trouble guard
-	if dpkg --compare-versions "$preversion" lt 2.35; then
+	if dpkg --compare-versions "$preversion" lt 2.31; then
 	    if pidof xscreensaver xlockmore >/dev/null; then
 		if [ "$USE_DEBCONF" ] ; then
 		    db_version 2.0
@@ -329,8 +430,8 @@ then
 		fi
 	    done
 
-            if [ -n "$services" ] && [ ! -x /usr/lib/needrestart/apt-pinvoke ]; then
-                if [ "$USE_DEBCONF" ] ; then
+            if [ -n "$services" ]; then
+                if [ -f /usr/share/debconf/confmodule ] ; then
                     db_version 2.0
                     if [ "$RELEASE_UPGRADE_MODE" = desktop ]; then
                         db_input medium libraries/restart-without-asking || true
@@ -411,7 +512,7 @@ then
             else
                 echo "Nothing to restart."
             fi
-	fi # end upgrading and $preversion lt 2.35
+	fi # end upgrading and $preversion lt 2.31
     fi # Upgrading
 
     # This will keep us from using hwcap libs (optimized) during an
@@ -422,12 +523,12 @@ fi
 
 
 if [ -n "$preversion" ]; then
-    if dpkg --compare-versions "$preversion" lt 2.35; then
+    if dpkg --compare-versions "$preversion" lt 2.31; then
        # unconditionally wipe ld.so.cache on major version upgrades; this
        # makes those upgrades a bit slower, but is less error-prone than
        # hoping we notice every time the cache format is changed upstream
-       rm -f "$DPKG_ROOT/etc/ld.so.cache"
-       rm -f "$DPKG_ROOT/var/cache/ldconfig/aux-cache"
+       rm -f /etc/ld.so.cache
+       rm -f /var/cache/ldconfig/aux-cache
     fi
 fi
 
diff --git a/assets/var/lib/dpkg/info/libpam0g:amd64.postinst b/assets/var/lib/dpkg/info/libpam0g:amd64.postinst
--- a/assets/var/lib/dpkg/info/libpam0g:amd64.postinst
+++ b/assets/var/lib/dpkg/info/libpam0g:amd64.postinst
@@ -52,45 +52,7 @@ filerc() {
     echo ""
 }
 
-if test -d /run/systemd/system; then
-    is_service_configured() {
-        systemctl is-enabled --quiet $1 || return 1
-    }
-    restart_service() {
-        if systemctl try-restart $1; then
-            :
-        else
-            failed="$failed $1"
-        fi
-    }
-else # not systemd
-    is_service_configured() {
-        service="$1"
-	idl="/etc/init.d/${service}"
-	if [ -n "$idl" ] && [ -x $idl ]; then
-	    return 0
-	else
-            return 1
-        fi
-    }
-
-    restart_service() {
-        service="$1"
-	idl="invoke-rc.d ${service}"
-	echo -n "  $service: stopping..." 2>&1
-	$idl stop > /dev/null 2>&1 || true
-	sleep 1
-	echo -n "starting..." 2>&1
-	if $idl start > /dev/null 2>&1; then
-	    echo "done." 2>&1
-	else
-	    echo "FAILED! ($?)" 2>&1
-	    failed="$service $failed"
-	fi
-    }
-fi
-    
-                 installed_services() {
+installed_services() {
     check="$@"
 
     # Only get the ones that are installed, and configured
@@ -112,10 +74,11 @@ fi
     )
 
     for service in $check; do
-	if is_service_configured $service; then
+	idl="/etc/init.d/${service}"
+	if [ -n "$idl" ] && [ -x $idl ]; then
 		services="$service $services"
 	else
-		echo "WARNING:  $service not configured." >&2
+		echo "WARNING: init script for $service not found." >&2
 	fi
     done
     echo "$services"
@@ -123,8 +86,8 @@ fi
 
 if [ "$1" = "configure" ]
 then
-    if [ ! -z "$2" ] && [ ! -x /usr/lib/needrestart/apt-pinvoke ]; then
-	if dpkg --compare-versions "$2" lt 1.4.0-2; then
+    if [ ! -z "$2" ]; then
+	if dpkg --compare-versions "$2" lt 1.3.1-2; then
 	    db_version 2.0
 
 	    echo -n "Checking for services that may need to be restarted..."
@@ -211,7 +174,16 @@ then
 				continue
 			    ;;
 			esac
-                        restart_service "$service"
+			echo -n "  $service: stopping..."
+			$idl stop > /dev/null 2>&1 || true
+			sleep 1
+			echo -n "starting..."
+			if $idl start > /dev/null 2>&1; then
+			    echo "done."
+			else
+			    echo "FAILED! ($?)"
+			    failed="$service $failed"
+			fi
 		    done
 		    echo
 		    if [ -n "$failed" ]; then
@@ -253,7 +225,7 @@ then
 	    # Shut down the frontend, to make sure none of the
 	    # restarted services keep a connection open to it
 	    db_stop
-	fi # end upgrading and $2 lt 1.4.0-2
+	fi # end upgrading and $2 lt 1.3.1-2
     fi # Upgrading
 fi
 
diff --git a/assets/var/lib/dpkg/info/util-linux.postinst b/assets/var/lib/dpkg/info/util-linux.postinst
--- a/assets/var/lib/dpkg/info/util-linux.postinst
+++ b/assets/var/lib/dpkg/info/util-linux.postinst
@@ -1,16 +1,18 @@
 #!/bin/sh
 set -e
 
-if [ "$(uname -s)" = "Linux" ]; then
-	update-alternatives --install /usr/bin/pager pager /bin/more 50 \
-		--slave /usr/share/man/man1/pager.1.gz pager.1.gz \
-		/usr/share/man/man1/more.1.gz
-fi
+update-alternatives --install /usr/bin/pager pager /bin/more 50 \
+	--slave /usr/share/man/man1/pager.1.gz pager.1.gz \
+	/usr/share/man/man1/more.1.gz
 
-# Automatically added by dh_installdeb/13.6ubuntu1
+# We stopped shipping the 'pg' utility, so remove it as a pager
+# alternative on upgrades from Stretch.
+update-alternatives --remove pager /usr/bin/pg
+
+# Automatically added by dh_installdeb/12.10ubuntu1
 dpkg-maintscript-helper rm_conffile /etc/cron.weekly/fstrim 2.31.1-0.4ubuntu1\~ -- "$@"
 # End automatically added section
-# Automatically added by dh_installsystemd/13.6ubuntu1
+# Automatically added by dh_installsystemd/12.10ubuntu1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'fstrim.timer' >/dev/null || true
@@ -27,7 +29,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.6ubuntu1
+# Automatically added by dh_installsystemd/12.10ubuntu1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -40,16 +42,30 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.6ubuntu1
+# Automatically added by dh_installsystemd/12.10ubuntu1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if deb-systemd-helper debian-installed 'fstrim.timer'; then
+		# This will only remove masks created by d-s-h on package removal.
+		deb-systemd-helper unmask 'fstrim.timer' >/dev/null || true
+
+		if deb-systemd-helper --quiet was-enabled 'fstrim.timer'; then
+			# Create new symlinks, if any.
+			deb-systemd-helper enable 'fstrim.timer' >/dev/null || true
+		fi
+	fi
+
+	# Update the statefile to add new symlinks (if any), which need to be cleaned
+	# up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state 'fstrim.timer' >/dev/null || true
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/12.10ubuntu1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
 		if [ -n "$2" ]; then
-			_dh_action=restart
-		else
-			_dh_action=start
+			deb-systemd-invoke try-restart 'fstrim.service' 'fstrim.timer' >/dev/null || true
 		fi
-		deb-systemd-invoke $_dh_action 'fstrim.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
